title: Welcome to my personal Github site!
description: I am a computational mathematician focus on both of the theoretical and engineering aspects of image processing, including normalization, harmonization, registration, and segmentation, etc.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
